### ISSUE TITLE
Can not load .so library when using SqlCipher from opensrp-client-core

### ISSUE THREAD

**Issue by baksosapi** [OpenSRP/opensrp-client-facial-recognition#1]
FR using native library under 
```
| - lib_name
| | - src
| | | - main
| | | | -jniLibs
| | | | - armeabi
| | | | | - .so
```
or
```
| - lib_name
| | - libs
| | | - armeabi
| | | | - .so
```
Based on test with several native library (.so file), every .so library can not load into the device (under directory [package_name]/lib ) when using sqlchiper by adding via gradle ```compile 'net.zetetic:android-database-sqlcipher:3.x.x@aar'```. 

I found the problem already post  [here](https://discuss.zetetic.net/t/facial-recognition-and-sqlcipher/402), but no response.
"When SQLCipher is removed from the project the facial recognition works fine again."

any solution ?

**Comment by ekigamba** [comment]
Yet to conclude investigating the said behaviour. Which android version does your device have?

**Comment by ekigamba** [comment]
@baksosapi  Try and check if the feature is supported without the opensrp-facial-recognition library?

**Comment by baksosapi** [comment]
I found the problem solved by load opensrp-facial-recognition library as local AAR.
thanks @keymane  and @ekigamba

**Comment by ekigamba** [comment]
@baksosapi Welcome. Just curious, which device are you using? Which snapdragon processor does it have?
